### ISSUE TITLE
bq40z50-R1 EOL

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/eps-hardware#5]
confirm that bq40z50-R2 is a direct replacement: pin compatible, function near identical, performance near identical.

**Comment by Alenux55** [comment]
This is getting replaced with [bq25703arsnt](https://www.digikey.ca/product-detail/en/texas-instruments/BQ25703ARSNT/296-46956-1-ND/7400157), is that correct?

**Comment by TobiNakamura** [comment]
bq40z50-R2 is also being replaced by bq25703arsnt as @Alenux55 has noted.
